### ISSUE TITLE
angular.factory declaration

### ISSUE THREAD

**Issue by vmlf01** [tomas-sereikis/Angular-Storage#2]
Just curious, why do you use a singleton factory function when the angular.factory method already does that for you? Am I missing something?

**Comment by tomas-sereikis** [comment]
lets say that you have a factory witch code like:

``` javascript
    .factory('SomeFactory', [..., function (...) {
        console.log('creating factory instance...');
        return { ...
```

If you will work with one module injected you will see that the console.log message will appear only once, but if you have a couple of modules implementing these factories you will get couple of console.log messages. I could just write something like 

e.g.

``` javascript
    .factory('SomeFactory', [..., function (...) {
        return {
            get: ...,
            put: ...
```

but i would have to duplicate StorageAbstract function content to each $localStorage and $sessionStorage factories. So my solution is to use my own singleton so i can use the same created instances in any module, not to let it recreate it.

Hope it explains if not just tell, ill try to get more detailed.

**Comment by vmlf01** [comment]
Oh, I see what you mean, didn't think of that!
Thanks.
